version: '3'
services:
    php:
        build:
            context: ./docker/php # своя сборка образа на основании dockerfile
        #image: php:8.2.3-fpm
        volumes:
            - ./:/var/www/project # ниже в образе nginx тоже изменить

    nginx:
        image: nginx:latest # используем последний стабильный образ nginx
        ports:
            - 8080:80 # маршрутизируем порты
        volumes:
            - ./:/var/www/project # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
            - ./docker/nginx:/etc/nginx/conf.d
        depends_on:
            - php

    mysql:
        image: mysql:8
        #container_name: mysql8 # можно задать имя контейнера
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root # задаем пароль для root пользователя
            #- MYSQL_USER=user
        volumes:
            - ../../data/mysql:/var/lib/mysql
